homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 9
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

# Hardware ###############################################################

discovery:

zwave:
 usb_path: /dev/ttyACM0

hue:

xiaomi_aqara:
  discovery_retry: 15
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_key

# logging ################################################################

logbook:
recorder:
  purge_keep_days: 7
  db_url: !secret my_db

# ui  #####################################################################

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url

#Node-Red iframe
panel_iframe:
 nodered:
   title: 'Node-Red'
   icon: 'mdi:shuffle-variant'
   url: 'http://192.168.1.26:1880/'

frontend:

config:

map:

sun:

# cloud ###################################################################

cloud:
  google_actions:
    filter:
      include_domains:
        - scene
        - script
# weather ################################################################
weather:
  - platform: buienradar
# includes ###############################################################

group: !include groups.yaml
automation: !include_dir_list automations/
script: !include scripts.yaml
scene: !include_dir_list scenes/
sensor: !include sensors.yaml
logger: !include logger.yaml
media_player: !include mediaplayers.yaml
mqtt: !include mqtt.yaml
history: !include history.yaml
device_tracker: !include devicetrackers.yaml
switch: !include switches.yaml
notify: !include notify.yaml
input_boolean: !include input_boolean.yaml

# rest ###################################################################
# Geccorrigeerde stand ivm metervervanging. Stand oude meter: 3746
rest_command:
  post_meterstanden:
    method: POST
    url: 'https://www.mindergas.nl/api/gas_meter_readings'
    headers:
      content-type: application/json
      AUTH-TOKEN: !secret token
    payload: '{ "date": "{{(as_timestamp(now()) - (24*3600)) | timestamp_custom(''%Y-%m-%d'', True) }}", "reading" : "{{states.sensor.gas_consumption.state | float + 3746.0 }}" }'


climate: 
  - platform: mqtt 
    qos: 1 
    name: Badkamer Thermostaat
    current_temperature_topic: thermostat/badkamer/current_temperature 
    temperature_state_topic: thermostat/badkamer/target_temperature 
    temperature_command_topic: thermostat/badkamer/target_temperature/set 
    mode_state_topic: thermostat/badkamer/mode 
    mode_command_topic: thermostat/badkamer/mode/set 
    away_mode_state_topic: thermostat/badkamer/away 
    away_mode_command_topic: thermostat/badkamer/away/set
    payload_on: 'on'
    payload_off: 'off'
    modes: 
      - heat 
      - manual 
      - boost 
      - eco
  
  - platform: mqtt 
    qos: 1 
    name: Slaapkamer Jorn Thermostaat
    current_temperature_topic: thermostat/slaapkamer_jorn/current_temperature 
    temperature_state_topic: thermostat/slaapkamer_jorn/target_temperature 
    temperature_command_topic: thermostat/slaapkamer_jorn/target_temperature/set 
    mode_state_topic: thermostat/slaapkamer_jorn/mode 
    mode_command_topic: thermostat/slaapkamer_jorn/mode/set 
    away_mode_state_topic: thermostat/slaapkamer_jorn/away 
    away_mode_command_topic: thermostat/slaapkamer_jorn/away/set
    payload_on: 'on'
    payload_off: 'off'
    modes: 
      - heat 
      - manual 
      - boost 
      - eco
  
  - platform: mqtt 
    qos: 1 
    name: Slaapkamer Juul Thermostaat
    current_temperature_topic: thermostat/slaapkamer_juul/current_temperature 
    temperature_state_topic: thermostat/slaapkamer_juul/target_temperature 
    temperature_command_topic: thermostat/slaapkamer_juul/target_temperature/set 
    mode_state_topic: thermostat/slaapkamer_juul/mode 
    mode_command_topic: thermostat/slaapkamer_juul/mode/set 
    away_mode_state_topic: thermostat/slaapkamer_juul/away 
    away_mode_command_topic: thermostat/slaapkamer_juul/away/set
    payload_on: 'on'
    payload_off: 'off'
    modes: 
      - heat 
      - manual 
      - boost 
      - eco