homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 9
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

# Hardware ###############################################################

discovery:

zwave:
 usb_path: /dev/ttyACM0

tradfri:
  host: 192.168.1.119

hue:

xiaomi_aqara:
  discovery_retry: 15
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_key
  
# logging ################################################################

logbook:
recorder:
  purge_keep_days: 100
  db_url: !secret my_db

# ui  #####################################################################

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secrets base_url
  cors_allowed_origins:
    - https://reformedreality.com
    - http://reformedreality.com

#Node-Red iframe
panel_iframe:
 nodered:
   title: 'Node-Red'
   icon: 'mdi:shuffle-variant'
   url: 'http://192.168.1.26:1880/'

frontend:

config:

# speech ##################################################################

tts:
  - platform: google

# location and time #######################################################

map:

sun:

# cloud ###################################################################

cloud:
  google_actions:
    filter:
      include_entities:
        - group.wc
        - group.woonkamer
    entity_config:
      group.wc:
        name: Toilet
      group.woonkamer:
        name: Living room          

# includes ###############################################################

group: !include groups.yaml
automation: !include_dir_list automations/
script: !include_dir_list scripts/
scene: !include_dir_list scenes/
sensor: !include sensors.yaml
logger: !include logger.yaml
media_player: !include mediaplayers.yaml
mqtt: !include mqtt.yaml
history: !include history.yaml
device_tracker: !include devicetrackers.yaml
switch: !include switches.yaml
notify: !include notify.yaml

# rest ###################################################################
# Geccorrigeerde stand ivm metervervanging. Stand oude meter: 3746
rest_command:
  post_meterstanden:
    method: POST
    url: 'https://www.mindergas.nl/api/gas_meter_readings'
    headers:
      content-type: application/json
      AUTH-TOKEN: !secret token
    payload: '{"date" : "{{states.sensor.yesterday.state}}","reading" : {{ states.sensor.gas_consumption.state | float + 3746 }}}'

