alias: PS4 max playtime enforcer
trigger:
  - platform: time
    minutes: '/5'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: media_player.playstation_4
      state: 'Playing'
    - condition: template
      value_template: '{{ states.sensor.ps4_vandaag.state | float > 2 }}'
action:
  - service: tts.google_say
    entity_id: media_player.living_room
    data:
      message: Now, young Skywalker, your playstation will die
  - service: media_player.turn_off
    entity_id: media_player.playstation_4
  - service: mediaplayer.turn_off
    entity_id: media_player.sony_bravia_tv