alias: ps4 notifier
trigger:
  - platform: time
    minutes: '/5'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: switch.playstation4
      state: 'on'
    - condition:  state
      entity_id: input_boolean.ps4_alarm
      state: 'on'
    - condition: template
      value_template: '{{ states.sensor.ps4_today.state | float > 2 }}'
action:
  - service: homeassistant.turn_on
    entity_id: script.ps4_notify