alias: PS4 max playtime enforcer
trigger:
  - platform: time
    minutes: '/5'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: media_player.playstation_4
      state: 'playing'
    - condition: template
      value_template: '{{ states.sensor.ps4_vandaag.state | float > 2 }}'
action:
  - service: script.turn_on
    entity_id: script.say
    data:
      variables:
        master: 'media_player.tv'
        where: 'media_player.living_room'
        volume: '1'
        what: 'Young Skywalker, your playstation will die now'
  - service: media_player.turn_off
    entity_id: media_player.playstation_4
  - service: mediaplayer.turn_off
    entity_id: media_player.sony_bravia_tv