alias: 'Jorn Set Location Not_Home'
initial_state: 'on'
trigger:
  platform: mqtt
  topic: !secret samsungs5_mqtt_topic
condition:
  condition: numeric_state
  entity_id: sensor.kasia_s5_presence
  below: 50
  value_template: '{{ state.state }}'
action:
  service: mqtt.publish
  data_template:
    topic: 'location/peter_s5'
    retain: true
    payload: 'not_home'
