alias: 'Jorn Set Location Home'
initial_state: 'on'
trigger:
  platform: mqtt
  topic: '!secret honor_9_mqtt_topic'
condition:
  condition: numeric_state
  entity_id: sensor.jorn_honor_9_presence
  above: 50
  value_template: '{{ state.state }}'
action:
  service: mqtt.publish
  data_template:
    topic: 'location/jorn_honor_9'
    retain: true
    payload: 'home'

